import { Chat, Message, StatusStory, CallLog, UserProfile, ContactGroup } from './types';

export const CURRENT_USER: UserProfile = {
  id: 'me',
  name: 'أنا (حسابي)',
  phone: '+20 100 123 4567',
  about: 'لا تقل مستحيل ما دام الله معك ✨ | متاح للعمل',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
};

export const INITIAL_CHATS: Chat[] = [
  {
    id: 'chat-1',
    name: 'أحمد محمد',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
    phone: '+20 109 876 5432',
    about: 'الحمد لله دائماً وأبداً 🤲',
    unreadCount: 2,
    onlineStatus: 'online',
    isPinned: true,
    lastMessage: {
      text: 'تمام هكون عندك على الساعة ٧ بإذن الله',
      timestamp: '16:25',
      type: 'text',
      senderId: 'chat-1',
      status: 'delivered',
    },
  },
  {
    id: 'chat-2',
    name: 'سارة علي 💻',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    phone: '+966 50 123 9988',
    about: 'Software Engineer | Keep learning 🚀',
    unreadCount: 0,
    onlineStatus: 'offline',
    lastSeen: 'اليوم الساعة 4:10 م',
    isPinned: true,
    lastMessage: {
      text: 'تسجيل صوتي (0:24)',
      timestamp: '15:42',
      type: 'voice',
      senderId: 'chat-2',
      status: 'read',
    },
  },
  {
    id: 'chat-3',
    name: 'عائلة البركة 👨‍👩‍👧‍👦',
    avatar: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=200&auto=format&fit=crop&q=80',
    about: 'المجموعة الرسمية للعائلة المباركة ❤️',
    isGroup: true,
    groupMembers: ['أنا', 'أحمد محمد', 'ماما', 'بابا', 'سارة'],
    unreadCount: 5,
    onlineStatus: 'offline',
    lastMessage: {
      text: 'ماما: ما تنسوش تجمعنا يوم الجمعة القادم',
      timestamp: '14:15',
      type: 'text',
      senderId: 'mom',
      status: 'delivered',
    },
  },
  {
    id: 'chat-4',
    name: 'م. كريم السيد (مدير المشروع)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    phone: '+971 55 432 1098',
    about: 'Product Manager @ TechHub',
    unreadCount: 0,
    onlineStatus: 'online',
    lastMessage: {
      text: 'الملف ممتاز جداً، اعتمدناه خلاص!',
      timestamp: '11:05',
      type: 'text',
      senderId: 'me',
      status: 'read',
    },
  },
  {
    id: 'chat-5',
    name: 'فريق التطوير 🚀 Tech Team',
    avatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80',
    about: 'React, Node, Cloud & Mobile discussions',
    isGroup: true,
    groupMembers: ['أنا', 'كريم', 'سارة', 'عمر', 'خالد'],
    unreadCount: 0,
    onlineStatus: 'offline',
    lastMessage: {
      text: 'تم عمل استطلاع رأي لموعد الاجتماع',
      timestamp: 'أمس',
      type: 'poll',
      senderId: 'chat-4',
      status: 'read',
    },
  },
  {
    id: 'chat-6',
    name: 'د. محمود حسن',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&auto=format&fit=crop&q=80',
    phone: '+20 122 998 7766',
    about: 'استشاري التغذية والصحة العامة',
    unreadCount: 0,
    onlineStatus: 'offline',
    lastSeen: 'أمس في 10:20 م',
    isArchived: true,
    lastMessage: {
      text: 'ألف سلامة عليك، النتيجة ممتازة استمر على الدواء',
      timestamp: 'أمس',
      type: 'text',
      senderId: 'chat-6',
      status: 'read',
    },
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  'chat-1': [
    {
      id: 'm1-1',
      chatId: 'chat-1',
      senderId: 'chat-1',
      text: 'السلام عليكم ورحمة الله، كيفك يا غالي؟ عساك بخير',
      timestamp: '16:15',
      status: 'read',
      type: 'text',
    },
    {
      id: 'm1-2',
      chatId: 'chat-1',
      senderId: 'me',
      text: 'وعليكم السلام ورحمة الله وبركاته يا أحمد! الحمد لله بأحسن حال، إنت كيفك؟',
      timestamp: '16:18',
      status: 'read',
      type: 'text',
      reactions: { '❤️': ['chat-1'] },
    },
    {
      id: 'm1-3',
      chatId: 'chat-1',
      senderId: 'me',
      text: 'كنت عاوز أسألك، هتقدر نتقابل النهاردة في الكافيه؟',
      timestamp: '16:20',
      status: 'read',
      type: 'text',
    },
    {
      id: 'm1-4',
      chatId: 'chat-1',
      senderId: 'chat-1',
      text: 'أكيد طبعاً، مشتاقين نقعد سوا ونتكلم في المشروع الجديد',
      timestamp: '16:22',
      status: 'read',
      type: 'text',
      reactions: { '👍': ['me'] },
    },
    {
      id: 'm1-5',
      chatId: 'chat-1',
      senderId: 'chat-1',
      text: 'تمام هكون عندك على الساعة ٧ بإذن الله',
      timestamp: '16:25',
      status: 'delivered',
      type: 'text',
    },
    {
      id: 'm1-6',
      chatId: 'chat-1',
      senderId: 'chat-1',
      text: 'كنت كاتب كلام ومسحته، بس أنت في الواتس الذهبي هتشوفه عادي! 😎✌️',
      timestamp: '16:26',
      status: 'read',
      type: 'text',
      isDeletedBySender: true,
    },
    {
      id: 'm1-7',
      chatId: 'chat-1',
      senderId: 'chat-1',
      text: 'صورة عرض لمرة واحدة 📸 (يمكنك فتحها وحفظها بلا حدود)',
      mediaUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
      timestamp: '16:28',
      status: 'read',
      type: 'image',
      isViewOnce: true,
    },
  ],

  'chat-2': [
    {
      id: 'm2-1',
      chatId: 'chat-2',
      senderId: 'me',
      text: 'أهلاً سارة، هل جربتي الواجهة الجديدة اللي جهزناها؟',
      timestamp: '15:30',
      status: 'read',
      type: 'text',
    },
    {
      id: 'm2-2',
      chatId: 'chat-2',
      senderId: 'chat-2',
      text: 'أهلاً بك! أيوا بصراحة التصميم طالع احترافي جداً وسلس بشكل رهيب 🔥',
      timestamp: '15:35',
      status: 'read',
      type: 'text',
      reactions: { '🔥': ['me'] },
    },
    {
      id: 'm2-3',
      chatId: 'chat-2',
      senderId: 'chat-2',
      timestamp: '15:42',
      status: 'read',
      type: 'voice',
      mediaDuration: 24,
      voiceWaveform: [30, 45, 60, 20, 80, 95, 40, 70, 85, 30, 50, 90, 75, 60, 40, 85, 100, 70, 55, 30, 65, 45, 80, 25],
    },
  ],

  'chat-3': [
    {
      id: 'm3-1',
      chatId: 'chat-3',
      senderId: 'chat-1',
      senderName: 'أحمد',
      text: 'جمعة مباركة مقدماً على الجميع يا أحلى عائلة 🌹',
      timestamp: '13:00',
      status: 'read',
      type: 'text',
      reactions: { '❤️': ['me', 'mom'] },
    },
    {
      id: 'm3-2',
      chatId: 'chat-3',
      senderId: 'mom',
      senderName: 'ماما',
      text: 'علينا وعليكم يا رب بالخير والبركة، ما تنسوش تجمعنا يوم الجمعة القادم',
      timestamp: '14:15',
      status: 'delivered',
      type: 'text',
    },
  ],

  'chat-4': [
    {
      id: 'm4-1',
      chatId: 'chat-4',
      senderId: 'chat-4',
      text: 'صباح الخير، محتاجين نراجع ملف العرض الفني النهائي مع التيم اليوم',
      timestamp: '10:00',
      status: 'read',
      type: 'text',
    },
    {
      id: 'm4-2',
      chatId: 'chat-4',
      senderId: 'me',
      text: 'صباح النور يا بشمهندس كريم، تفضل هذا هو الملف جاهز بالكامل:',
      timestamp: '10:45',
      status: 'read',
      type: 'document',
      mediaName: 'العرض_الفني_والتسليم_النهائي.pdf',
      mediaSize: '3.4 MB',
    },
    {
      id: 'm4-3',
      chatId: 'chat-4',
      senderId: 'me',
      text: 'الملف ممتاز جداً، اعتمدناه خلاص!',
      timestamp: '11:05',
      status: 'read',
      type: 'text',
      reactions: { '👏': ['chat-4'] },
    },
  ],

  'chat-5': [
    {
      id: 'm5-1',
      chatId: 'chat-5',
      senderId: 'chat-4',
      senderName: 'م. كريم',
      text: 'شباب، محتاجين نحدد موعد الـ Sprint Planning لهذا الأسبوع',
      timestamp: 'أمس 11:20',
      status: 'read',
      type: 'poll',
      pollData: {
        question: 'ما هو الموعد الأنسب لاجتماع الـ Sprint القادم؟',
        allowMultiple: false,
        options: [
          { id: 'opt-1', text: 'الأحد 10:00 صباحاً', votes: ['chat-2', 'me'] },
          { id: 'opt-2', text: 'الإثنين 11:00 صباحاً', votes: ['chat-4'] },
          { id: 'opt-3', text: 'الثلاثاء بعد الظهر', votes: [] },
        ],
      },
    },
  ],

  'chat-6': [
    {
      id: 'm6-1',
      chatId: 'chat-6',
      senderId: 'me',
      text: 'دكتور محمود، أرسلت لك نتائج التحاليل أمس هل اطلعت عليها؟',
      timestamp: 'أمس 09:30',
      status: 'read',
      type: 'text',
    },
    {
      id: 'm6-2',
      chatId: 'chat-6',
      senderId: 'chat-6',
      text: 'ألف سلامة عليك، النتيجة ممتازة استمر على الدواء وموعدنا الأسبوع القادم للمتابعة',
      timestamp: 'أمس 10:20',
      status: 'read',
      type: 'text',
    },
  ],
};

export const INITIAL_STATUSES: StatusStory[] = [
  {
    id: 's-1',
    userId: 'chat-1',
    userName: 'أحمد محمد',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
    timestamp: 'منذ 35 دقيقة',
    type: 'image',
    content: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    seen: false,
  },
  {
    id: 's-2',
    userId: 'chat-2',
    userName: 'سارة علي 💻',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    timestamp: 'منذ ساعتين',
    type: 'text',
    content: '«النجاح ليس عدم ارتكاب الأخطاء، بل عدم تكرار نفس الخطأ مرتين» ☕💻',
    bgColor: '#128c7e',
    seen: false,
  },
  {
    id: 's-3',
    userId: 'chat-4',
    userName: 'م. كريم السيد',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    timestamp: 'منذ 5 ساعات',
    type: 'image',
    content: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    seen: true,
  },
];

export const INITIAL_CALLS: CallLog[] = [
  {
    id: 'call-1',
    contactId: 'chat-1',
    contactName: 'أحمد محمد',
    contactAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
    timestamp: 'اليوم 15:10',
    type: 'incoming',
    isVideo: false,
    duration: 184,
  },
  {
    id: 'call-2',
    contactId: 'chat-2',
    contactName: 'سارة علي 💻',
    contactAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    timestamp: 'أمس 18:40',
    type: 'outgoing',
    isVideo: true,
    duration: 520,
  },
  {
    id: 'call-3',
    contactId: 'chat-4',
    contactName: 'م. كريم السيد',
    contactAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    timestamp: 'أمس 12:15',
    type: 'missed',
    isVideo: false,
  },
];

export const CONTEXTUAL_REPLIES: Record<string, string[]> = {
  general: [
    'تسلم يا غالي، كلك ذوق والله! 🌹',
    'تمام جداً، معاك إن شاء الله.',
    'وصلت الفكرة يا باشا، ممتاز!',
    'ما شاء الله، شغل عالي ومجهود تشكر عليه 👏',
    'أنا براجع الموضوع وهرد عليك حالاً.',
    'تمام متفقين تماماً، نلتقي قريباً!',
    'حبيبي يا أخي، تسلم إيدك 🙏',
    'الله يعطيك العافية، شكراً جزيلاً',
  ],
};

export const DEFAULT_GOLD_PRIVACY = {
  hideLastSeen: true,
  freezeLastSeenDate: '2026/09/25 10:30 م',
  hideBlueTicksContacts: true,
  hideBlueTicksGroups: false,
  hideSecondTickContacts: false,
  hideSecondTickGroups: false,
  hideTypingContacts: true,
  hideTypingGroups: false,
  hideRecording: true,
  hideBlueMicrophone: true,
  hideStatusView: true,
  antiDeleteMessages: true,
  antiDeleteStatus: true,
  disableForwardedTag: true,
  allowUnlimitedViewOnce: true,
  dndInternetCut: false,
};

export const INITIAL_ACCOUNTS = [
  {
    id: 'acc-1',
    slotNumber: 1,
    name: 'حسابي الأساسي (مصر)',
    phone: '+20 100 123 4567',
    about: 'الواتساب الذهبي الأصلي V12 ✨',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'acc-2',
    slotNumber: 2,
    name: 'رقم العمل الثاني (السعودية)',
    phone: '+966 50 999 8877',
    about: 'متاح لأعمال البرمجة والاستشارات 💼',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'acc-3',
    slotNumber: 3,
    name: 'الرقم الإماراتي الثالث',
    phone: '+971 50 444 3322',
    about: 'Tech & Innovation Dubai 🇦🇪',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'acc-4',
    slotNumber: 4,
    name: 'الرقم التجاري الرابع',
    phone: '+20 111 222 3344',
    about: 'متجر الخدمات الإلكترونية 🛍️',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'acc-5',
    slotNumber: 5,
    name: 'الرقم الخامس الشخصي',
    phone: '+1 415 555 2671',
    about: 'Private & Encrypted 🔐',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
  },
];

export const GOLD_THEMES_CATALOG = [
  {
    id: 'gold',
    name: 'الذهبي الفاخر (Gold Luxury)',
    category: 'الذهبي الملكي',
    downloads: '2.4M',
    accentColor: '#d4af37',
    headerBg: '#1f1b0a',
    chatBg: '#131107',
    previewBadge: 'ذهبي أصلي',
    description: 'الثيم الأيقوني لواتساب الذهبي بالأزرار الذهبية والواجهة الملكية',
  },
  {
    id: 'classic-green',
    name: 'الافتراضي الكلاسيكي (Green Classic)',
    category: 'أخضر رسمي',
    downloads: '1.8M',
    accentColor: '#00a884',
    headerBg: '#202c33',
    chatBg: '#0b141a',
    previewBadge: 'كلاسيك',
    description: 'اللون الأخضر المعتاد لواجهة واتساب الأصلية مع ميزات الذهبي',
  },
  {
    id: 'dark-gold',
    name: 'الأسود والذهب الليلي (OneUI Dark Gold)',
    category: 'أمورفيا داكن',
    downloads: '950K',
    accentColor: '#e5b839',
    headerBg: '#0a0a0a',
    chatBg: '#050505',
    previewBadge: 'AMOLED',
    description: 'شاشة سوداء خالصة موفرة للطاقة مع حواف ولمسات ذهبية براقة',
  },
  {
    id: 'oneui-dark',
    name: 'سامسونج OneUI Dark',
    category: 'OneUI',
    downloads: '820K',
    accentColor: '#0381fe',
    headerBg: '#121212',
    chatBg: '#0d0d0d',
    previewBadge: 'Samsung',
    description: 'تصميم OneUI الأنيق مع خطوط دائرية وألوان ناعمة ومريحة للعين',
  },
  {
    id: 'ios-dark',
    name: 'آيفون الذهبي (iOS Dark Gold)',
    category: 'Apple iOS',
    downloads: '1.2M',
    accentColor: '#ffcc00',
    headerBg: '#1c1c1e',
    chatBg: '#000000',
    previewBadge: 'iOS 18',
    description: 'واجهة iOS الشهيرة بأيقونات الآيفون وفقاعات الرسائل المستديرة',
  },
  {
    id: 'royal-black',
    name: 'الملكي الأسود (Royal Black)',
    category: 'ملكي فاخر',
    downloads: '740K',
    accentColor: '#c59b27',
    headerBg: '#18181b',
    chatBg: '#09090b',
    previewBadge: 'VIP',
    description: 'تدرج فخم من الرمادي الداكن والأسود المذهب لرجال الأعمال',
  },
];

export const INITIAL_CONTACT_GROUPS: ContactGroup[] = [
  {
    id: 'cg-family',
    name: 'العائلة (Family)',
    color: '#ef4444', // Red
    chatIds: ['chat-3', 'chat-1'],
  },
  {
    id: 'cg-work',
    name: 'العمل (Work)',
    color: '#3b82f6', // Blue
    chatIds: ['chat-2', 'chat-4', 'chat-5', 'chat-6'],
  },
  {
    id: 'cg-friends',
    name: 'الأصدقاء (Friends)',
    color: '#10b981', // Emerald
    chatIds: ['chat-1', 'chat-2'],
  },
  {
    id: 'cg-vip',
    name: 'المقربون (VIP)',
    color: '#eab308', // Gold / Amber
    chatIds: ['chat-1', 'chat-4'],
  },
];

